Merged PR 7494: BUG/TEST: Fixed various bugs in Usage Sharing and added tests.
BUG: Logged correctly to the logger from pipeline when an error occurs in usage sharing.
BUG: Share percentage is now implemented correctly in share usage. A comment has been added to explain how to use this value.
FEAT: The share endpoint is now configurable. This is used for unit tests.
FEAT: Added required details to usage records, e.g. client IP
REORG: Aligned share usage filter to other languages.
TEST: Added unit tests for share usage to confirm bugs are fixed.

Related work items: #4969, #4970

diff --git a/ci/shared-build-and-test-stage.yml b/ci/shared-build-and-test-stage.yml
--- a/ci/shared-build-and-test-stage.yml
+++ b/ci/shared-build-and-test-stage.yml
@@ -133,6 +133,14 @@ stages:
           exit 1
         fi  
         cp .coverage ../.coverage.engines
+
+        cd ../fiftyone_pipeline_engines_fiftyone
+        coverage run -m xmlrunner discover -s tests -p test*.py -o test-results
+        if [ $? -ne 0 ]; then
+          echo "Failed to run test cases and coverage for fiftyone_pipeline_engines_fiftyone."
+          exit 1
+        fi  
+        cp .coverage ../.coverage.engines.fiftyone
         cd ..
         coverage combine 
         coverage xml
